### ISSUE TITLE
Tracking missing and broken things

### ISSUE THREAD

**Issue by FelixCCWork** [Felix-CodingClimber/DotNetElements.Wpf.Markdown#1]
- [x] Fix nested styles, sub & super (see https://github.com/CommunityToolkit/Labs-Windows/pull/614)
- [x] Implement github alert container extension (see https://github.com/xoofx/markdig/blob/master/src/Markdig.Tests/Specs/AlertBlockSpecs.md)
- [x] Add OnMarkdownParsed event (see https://github.com/CommunityToolkit/Labs-Windows/pull/616)
- [ ] Check how to implement extensions ( see https://github.com/CommunityToolkit/Labs-Windows/issues/609)
- [x] #4
  - https://github.com/coltrane2ny/Markdig.Wpf.ColorCode
  - https://github.com/coltrane2ny/ColorCode-WPF
  - https://github.com/CommunityToolkit/ColorCode-Universal

**Comment by Felix-CodingClimber** [comment]
Moved to separate issues
